//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FedoRomance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostID { get; set; }
        public string Message { get; set; }
        public int PostedBy { get; set; }
        public int PostedTo { get; set; }
        public string Poster { get; set; }
        public string Receiver { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
